# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fog.proto',
  package='foghandoff',
  syntax='proto2',
  serialized_options=_b('\n\016foghandoff.fogB\013FogMessages'),
  serialized_pb=_b('\n\tfog.proto\x12\nfoghandoff\"/\n\rAcceptMessage\x12\r\n\x05\x66ogId\x18\x01 \x02(\t\x12\x0f\n\x07jobPort\x18\x02 \x02(\x05\"w\n\x11\x43onnectionMessage\x12\x0e\n\x06\x65\x64geId\x18\x01 \x02(\t\x12\x32\n\x04type\x18\x02 \x02(\x0e\x32$.foghandoff.ConnectionMessage.OpType\"\x1e\n\x06OpType\x12\x07\n\x03NEW\x10\x00\x12\x0b\n\x07PREPARE\x10\x01\"o\n\x0cTaskMessagee\x12\x0e\n\x06\x65\x64geId\x18\x01 \x02(\t\x12/\n\x04type\x18\x02 \x02(\x0e\x32!.foghandoff.TaskMessagee.TaskType\"\x1e\n\x08TaskType\x12\x08\n\x04PING\x10\x00\x12\x08\n\x04KILL\x10\x01\"3\n\x10\x41llocatedMessage\x12\x0e\n\x06\x65\x64geId\x18\x01 \x02(\t\x12\x0f\n\x07jobPort\x18\x02 \x02(\x05\"/\n\x08Location\x12\x11\n\tlongitude\x18\x01 \x02(\x01\x12\x10\n\x08latitude\x18\x02 \x02(\x01\"/\n\x08Velocity\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\r\n\x05speed\x18\x03 \x02(\x02\x42\x1d\n\x0e\x66oghandoff.fogB\x0b\x46ogMessages')
)



_CONNECTIONMESSAGE_OPTYPE = _descriptor.EnumDescriptor(
  name='OpType',
  full_name='foghandoff.ConnectionMessage.OpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREPARE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=163,
  serialized_end=193,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIONMESSAGE_OPTYPE)

_TASKMESSAGEE_TASKTYPE = _descriptor.EnumDescriptor(
  name='TaskType',
  full_name='foghandoff.TaskMessagee.TaskType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KILL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=276,
  serialized_end=306,
)
_sym_db.RegisterEnumDescriptor(_TASKMESSAGEE_TASKTYPE)


_ACCEPTMESSAGE = _descriptor.Descriptor(
  name='AcceptMessage',
  full_name='foghandoff.AcceptMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fogId', full_name='foghandoff.AcceptMessage.fogId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jobPort', full_name='foghandoff.AcceptMessage.jobPort', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=72,
)


_CONNECTIONMESSAGE = _descriptor.Descriptor(
  name='ConnectionMessage',
  full_name='foghandoff.ConnectionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edgeId', full_name='foghandoff.ConnectionMessage.edgeId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='foghandoff.ConnectionMessage.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONNECTIONMESSAGE_OPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=193,
)


_TASKMESSAGEE = _descriptor.Descriptor(
  name='TaskMessagee',
  full_name='foghandoff.TaskMessagee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edgeId', full_name='foghandoff.TaskMessagee.edgeId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='foghandoff.TaskMessagee.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASKMESSAGEE_TASKTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=306,
)


_ALLOCATEDMESSAGE = _descriptor.Descriptor(
  name='AllocatedMessage',
  full_name='foghandoff.AllocatedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edgeId', full_name='foghandoff.AllocatedMessage.edgeId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jobPort', full_name='foghandoff.AllocatedMessage.jobPort', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=359,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='foghandoff.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='foghandoff.Location.longitude', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='foghandoff.Location.latitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=408,
)


_VELOCITY = _descriptor.Descriptor(
  name='Velocity',
  full_name='foghandoff.Velocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='foghandoff.Velocity.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='foghandoff.Velocity.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='foghandoff.Velocity.speed', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=457,
)

_CONNECTIONMESSAGE.fields_by_name['type'].enum_type = _CONNECTIONMESSAGE_OPTYPE
_CONNECTIONMESSAGE_OPTYPE.containing_type = _CONNECTIONMESSAGE
_TASKMESSAGEE.fields_by_name['type'].enum_type = _TASKMESSAGEE_TASKTYPE
_TASKMESSAGEE_TASKTYPE.containing_type = _TASKMESSAGEE
DESCRIPTOR.message_types_by_name['AcceptMessage'] = _ACCEPTMESSAGE
DESCRIPTOR.message_types_by_name['ConnectionMessage'] = _CONNECTIONMESSAGE
DESCRIPTOR.message_types_by_name['TaskMessagee'] = _TASKMESSAGEE
DESCRIPTOR.message_types_by_name['AllocatedMessage'] = _ALLOCATEDMESSAGE
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Velocity'] = _VELOCITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AcceptMessage = _reflection.GeneratedProtocolMessageType('AcceptMessage', (_message.Message,), dict(
  DESCRIPTOR = _ACCEPTMESSAGE,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:foghandoff.AcceptMessage)
  ))
_sym_db.RegisterMessage(AcceptMessage)

ConnectionMessage = _reflection.GeneratedProtocolMessageType('ConnectionMessage', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONMESSAGE,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:foghandoff.ConnectionMessage)
  ))
_sym_db.RegisterMessage(ConnectionMessage)

TaskMessagee = _reflection.GeneratedProtocolMessageType('TaskMessagee', (_message.Message,), dict(
  DESCRIPTOR = _TASKMESSAGEE,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:foghandoff.TaskMessagee)
  ))
_sym_db.RegisterMessage(TaskMessagee)

AllocatedMessage = _reflection.GeneratedProtocolMessageType('AllocatedMessage', (_message.Message,), dict(
  DESCRIPTOR = _ALLOCATEDMESSAGE,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:foghandoff.AllocatedMessage)
  ))
_sym_db.RegisterMessage(AllocatedMessage)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:foghandoff.Location)
  ))
_sym_db.RegisterMessage(Location)

Velocity = _reflection.GeneratedProtocolMessageType('Velocity', (_message.Message,), dict(
  DESCRIPTOR = _VELOCITY,
  __module__ = 'fog_pb2'
  # @@protoc_insertion_point(class_scope:foghandoff.Velocity)
  ))
_sym_db.RegisterMessage(Velocity)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
